import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { api, messageForError } from "../../api/client";
import type { CrmChildImportState, CrmChildPreview, CrmConnectionTestStatus, CrmIntegration } from "../../api/types";
import { useAuth } from "../../auth/AuthContext";
import { useToast } from "../../ui/Toast";
import { Failure, PageLoading } from "../dashboard/DashboardPage";
import { formatDate } from "../devices/DeviceBits";

const canManage = (role: string | null) => role === "OWNER" || role === "ADMIN";
const stateLabel: Record<CrmChildImportState, string> = { NOT_IMPORTED: "Не добавлен", IMPORTED: "Уже в Oyla", UPDATE_AVAILABLE: "Есть обновления", ARCHIVED_EXTERNAL: "В архиве CRM" };
const connectionLabel: Record<CrmConnectionTestStatus, string> = { SUCCESS: "Подключение подтверждено", AUTH_FAILED: "CRM отклонила API-ключ", UNREACHABLE: "CRM сейчас недоступна", INVALID_RESPONSE: "CRM вернула некорректный ответ", TIMEOUT: "CRM не ответила вовремя", TLS_ERROR: "Не удалось установить защищённое TLS-соединение" };

export function IntegrationsPage() {
  const { role } = useAuth(); const crm = useQuery({ queryKey: ["crm-integration"], queryFn: api.getCrmIntegration });
  if (crm.isLoading) return <PageLoading />;
  if (crm.isError) return <Failure message={messageForError(crm.error)} onRetry={() => void crm.refetch()} />;
  return <><div className="page-heading"><div><Link className="back-link" to="/settings">← Настройки</Link><p className="eyebrow">Настройки</p><h1>Интеграции</h1><p className="muted">Внешние системы подключаются только через сервер Oyla.</p></div></div><section className="panel"><div className="integration-card"><div><h2>CRM</h2><p className="muted">Односторонний ручной импорт и синхронизация детей из CRM.</p></div><div>{crm.data?.status === "ACTIVE" ? <span className="status-badge online">Подключено</span> : <span className="status-badge muted-badge">Не подключено</span>}</div><Link className="secondary-button" to="/settings/integrations/crm">Открыть CRM</Link></div>{!canManage(role) && <p className="muted">У вас нет доступа к настройке интеграций.</p>}</section></>;
}

export function CrmIntegrationPage() {
  const { role } = useAuth(); const toast = useToast(); const cache = useQueryClient(); const integration = useQuery({ queryKey: ["crm-integration"], queryFn: api.getCrmIntegration });
  const [editing, setEditing] = useState(false); const [importOpen, setImportOpen] = useState(false); const [baseUrl, setBaseUrl] = useState(""); const [name, setName] = useState("CRM"); const [testStatus, setTestStatus] = useState<CrmConnectionTestStatus | null>(null); const apiKeyRef = useRef<HTMLInputElement>(null);
  const managed = canManage(role); const connected = integration.data?.status === "ACTIVE";
  const beginEdit = () => { setEditing(true); setBaseUrl(integration.data?.baseUrl ?? ""); setName(integration.data?.name ?? "CRM"); setTestStatus(null); };
  const invalidate = () => void cache.invalidateQueries({ queryKey: ["crm-integration"] });
  const test = useMutation({ mutationFn: async () => api.testCrmIntegration({ baseUrl: baseUrl || undefined, apiKey: apiKeyRef.current?.value || undefined }), onSuccess: result => { setTestStatus(result.status); toast.show(connectionLabel[result.status], result.status === "SUCCESS" ? "success" : "error"); }, onError: error => toast.show(messageForError(error), "error") });
  const save = useMutation({ mutationFn: () => {
    const key = apiKeyRef.current?.value ?? "";
    if (connected) return api.updateCrmIntegration({ name, baseUrl: baseUrl || undefined, apiKey: key || undefined });
    return api.createCrmIntegration({ name, baseUrl, apiKey: key });
  }, onSuccess: () => { if (apiKeyRef.current) apiKeyRef.current.value = ""; invalidate(); setEditing(false); setTestStatus(null); toast.show("CRM подключена"); }, onError: error => toast.show(messageForError(error), "error") });
  const disconnect = useMutation({ mutationFn: api.disableCrmIntegration, onSuccess: () => { invalidate(); cache.invalidateQueries({ queryKey: ["children"] }); toast.show("CRM отключена. Импортированные дети и история сохранены."); }, onError: error => toast.show(messageForError(error), "error") });
  const sync = useMutation({ mutationFn: api.syncCrmChildren, onSuccess: result => { invalidate(); cache.invalidateQueries({ queryKey: ["children"] }); toast.show(`Проверено: ${result.checked}; обновлено: ${result.updated}; архивировано: ${result.archived}; восстановлено: ${result.restored}.`); }, onError: error => toast.show(messageForError(error), "error") });
  if (integration.isLoading) return <PageLoading />;
  if (integration.isError) return <Failure message={messageForError(integration.error)} onRetry={() => void integration.refetch()} />;
  if (!managed) return <><div className="page-heading"><div><Link className="back-link" to="/settings/integrations">← Интеграции</Link><p className="eyebrow">Интеграции</p><h1>CRM</h1></div></div><section className="panel narrow"><p className="muted">Доступ к настройкам CRM есть только у владельца и администратора центра.</p></section></>;
  const showForm = !connected || editing;
  return <><div className="page-heading"><div><Link className="back-link" to="/settings/integrations">← Интеграции</Link><p className="eyebrow">Интеграции</p><h1>CRM</h1><p className="muted">Oyla получает данные CRM только с сервера; API-ключ не передаётся браузеру после сохранения.</p></div>{connected && <span className="status-badge online">✓ Подключено</span>}</div>
    {showForm ? <section className="panel narrow"><h2>{connected ? "Изменить подключение" : "Подключить CRM"}</h2><form className="form-stack" onSubmit={event => { event.preventDefault(); save.mutate(); }}><label className="field"><span>Название</span><input value={name} onChange={event => setName(event.target.value)} maxLength={160} /></label><label className="field"><span>Адрес CRM</span><input value={baseUrl} onChange={event => setBaseUrl(event.target.value)} placeholder="https://crm.example.kz" required /></label><label className="field"><span>API-ключ</span><input ref={apiKeyRef} type="password" autoComplete="new-password" placeholder={connected ? "Оставьте пустым, чтобы не менять ключ" : "Введите API-ключ"} required={!connected} maxLength={4096} /></label>{testStatus && <p className={testStatus === "SUCCESS" ? "inline-success" : "field-error"}>{connectionLabel[testStatus]}</p>}<div className="dialog-actions"><button type="button" className="secondary-button" disabled={!baseUrl.trim() || test.isPending} onClick={() => test.mutate()}>{test.isPending ? "Проверяем…" : "Проверить подключение"}</button><button className="primary-button" disabled={save.isPending || (!connected && testStatus !== "SUCCESS")}>{save.isPending ? "Подключаем…" : connected ? "Сохранить изменения" : "Подключить"}</button>{connected && <button type="button" className="text-button" onClick={() => { setEditing(false); setTestStatus(null); }}>Отмена</button>}</div></form></section> : <ConnectedCrm integration={integration.data!} onImport={() => setImportOpen(true)} onEdit={beginEdit} onDisconnect={() => window.confirm("Отключить CRM? Импортированные дети, навыки и история занятий останутся в Oyla.") && disconnect.mutate()} onSync={() => sync.mutate()} syncing={sync.isPending} disconnecting={disconnect.isPending} />}
    {importOpen && <ImportChildrenDialog onClose={() => setImportOpen(false)} />}
  </>;
}

function ConnectedCrm({ integration, onImport, onEdit, onDisconnect, onSync, syncing, disconnecting }: { integration: CrmIntegration; onImport: () => void; onEdit: () => void; onDisconnect: () => void; onSync: () => void; syncing: boolean; disconnecting: boolean }) {
  return <section className="panel narrow"><h2>CRM</h2><dl className="details"><dt>Адрес</dt><dd>{integration.baseUrl}</dd><dt>API-ключ</dt><dd>••••••••••••</dd><dt>Последняя проверка</dt><dd>{formatDate(integration.lastConnectionCheckAt)}</dd><dt>Последняя синхронизация</dt><dd>{formatDate(integration.lastSuccessfulSyncAt)}</dd></dl><div className="dialog-actions"><button className="primary-button" onClick={onImport}>Импортировать детей</button><button className="secondary-button" onClick={onSync} disabled={syncing}>{syncing ? "Синхронизируем…" : "Синхронизировать"}</button><button className="text-button" onClick={onEdit}>Изменить</button><button className="danger-link" onClick={onDisconnect} disabled={disconnecting}>Отключить</button></div></section>;
}

function ImportChildrenDialog({ onClose }: { onClose: () => void }) {
  const toast = useToast(); const cache = useQueryClient(); const preview = useQuery({ queryKey: ["crm-children-preview"], queryFn: api.previewCrmChildren }); const [search, setSearch] = useState(""); const [filter, setFilter] = useState<"ALL" | CrmChildImportState>("NOT_IMPORTED"); const [selected, setSelected] = useState<Set<string>>(new Set());
  const visible = useMemo(() => (preview.data?.children ?? []).filter(child => (filter === "ALL" || child.importState === filter) && `${child.firstName} ${child.lastName}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())), [preview.data, filter, search]);
  const importChildren = useMutation({ mutationFn: () => api.importCrmChildren([...selected]), onSuccess: result => { cache.invalidateQueries({ queryKey: ["children"] }); cache.invalidateQueries({ queryKey: ["crm-children-preview"] }); toast.show(`Импортировано: ${result.imported}; обновлено: ${result.updated}.`); onClose(); }, onError: error => toast.show(messageForError(error), "error") });
  const toggle = (child: CrmChildPreview) => { if (child.importState === "IMPORTED") return; setSelected(current => { const next = new Set(current); next.has(child.externalId) ? next.delete(child.externalId) : next.add(child.externalId); return next; }); };
  return <div className="modal-backdrop" role="presentation"><section className="modal modal-wide" role="dialog" aria-modal="true" aria-label="Импорт детей из CRM"><button className="modal-close" onClick={onClose} aria-label="Закрыть">×</button><h2>Выберите детей из CRM</h2><div className="toolbar"><div className="filter-row">{(["ALL", "NOT_IMPORTED", "IMPORTED", "UPDATE_AVAILABLE"] as const).map(value => <button key={value} className={filter === value ? "filter active" : "filter"} onClick={() => setFilter(value)}>{value === "ALL" ? "Все" : stateLabel[value]}</button>)}</div><label className="search"><span className="sr-only">Поиск</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Поиск по имени" /></label></div>{preview.isLoading ? <PageLoading /> : preview.isError ? <Failure message={messageForError(preview.error)} onRetry={() => void preview.refetch()} /> : <div className="selection-list">{visible.map(child => <label key={child.externalId} className={child.importState === "IMPORTED" ? "selection-row disabled" : "selection-row"}><input type="checkbox" checked={selected.has(child.externalId)} disabled={child.importState === "IMPORTED"} onChange={() => toggle(child)} /><span><strong>{child.firstName} {child.lastName}</strong><small>{new Date(`${child.birthDate}T00:00:00`).getFullYear()} г. р. · {stateLabel[child.importState]}</small></span></label>)}{visible.length === 0 && <p className="empty-inline">Детей по этому фильтру нет.</p>}</div>}<div className="dialog-actions"><button className="primary-button" disabled={selected.size === 0 || importChildren.isPending} onClick={() => importChildren.mutate()}>{importChildren.isPending ? "Импортируем…" : `Импортировать ${selected.size}`}</button><button className="text-button" onClick={onClose}>Отмена</button></div></section></div>;
}
