import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, messageForError } from "../../api/client";
import type { ContentExercise, ContentExerciseOption, LessonTemplate } from "../../api/types";
import { Failure, PageLoading } from "../dashboard/DashboardPage";

const canEdit = (role?: string | null) => role === "OWNER" || role === "ADMIN" || role === "METHODIST";
type DraftOption = { id?: string; label: string; imageAssetId?: string; imageUrl?: string; isCorrect: boolean };

export function ExercisesPage() {
  const [scope, setScope] = useState<"ALL" | "SYSTEM" | "CENTER">("ALL"); const [status, setStatus] = useState<"ALL" | "ACTIVE" | "ARCHIVED">("ACTIVE"); const [search, setSearch] = useState("");
  const exercises = useQuery({ queryKey: ["content-exercises", scope, status, search], queryFn: () => api.listExercises({ ownership: scope === "ALL" ? undefined : scope, status: status === "ALL" ? undefined : status, search }) });
  if (exercises.isLoading) return <PageLoading />; if (exercises.error) return <Failure message={messageForError(exercises.error)} onRetry={() => void exercises.refetch()} />;
  return <><div className="page-heading"><div><p className="eyebrow">Контент</p><h1>Упражнения</h1><p className="muted">Библиотека Oyla и упражнения вашего центра.</p></div><Link className="primary-button" to="/content/exercises/new">+ Создать упражнение</Link></div>
    <section className="panel"><div className="toolbar"><div className="filter-row">{(["ALL", "SYSTEM", "CENTER"] as const).map(value => <button key={value} className={`filter ${scope === value ? "active" : ""}`} onClick={() => setScope(value)}>{value === "ALL" ? "Все" : value === "SYSTEM" ? "Oyla" : "Центра"}</button>)}{(["ACTIVE", "ARCHIVED", "ALL"] as const).map(value => <button key={value} className={`filter ${status === value ? "active" : ""}`} onClick={() => setStatus(value)}>{value === "ALL" ? "Все статусы" : value === "ACTIVE" ? "Активные" : "Архив"}</button>)}</div><label className="search"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Поиск упражнений" /></label></div>
      {exercises.data?.length ? <div className="table-wrap"><table><thead><tr><th>Название</th><th>Тип</th><th>Источник</th><th>Статус</th><th>В шаблонах</th></tr></thead><tbody>{exercises.data.map(exercise => <tr key={exercise.id}><td><Link className="table-link" to={`/content/exercises/${exercise.id}`}>{exercise.title}</Link></td><td>SINGLE_CHOICE</td><td><span className="status-badge muted-badge">{exercise.ownership === "SYSTEM" ? "Oyla" : "Моё"}</span></td><td>{exercise.status === "ACTIVE" ? "Активно" : "Архив"}</td><td>{exercise.templateUsageCount}</td></tr>)}</tbody></table></div> : <div className="empty-state"><p>Упражнений по этим фильтрам пока нет.</p></div>}</section></>;
}

export function ExerciseEditorPage() {
  const { exerciseId = "new" } = useParams(); const isNew = exerciseId === "new"; const navigate = useNavigate(); const cache = useQueryClient();
  const existing = useQuery({ queryKey: ["content-exercise", exerciseId], queryFn: () => api.getExercise(exerciseId), enabled: !isNew });
  const [title, setTitle] = useState(""); const [instruction, setInstruction] = useState(""); const [audioAssetId, setAudioAssetId] = useState<string | undefined>(); const [options, setOptions] = useState<DraftOption[]>(defaultOptions()); const [uploading, setUploading] = useState<number | "audio" | null>(null);
  useEffect(() => { if (existing.data) { setTitle(existing.data.title); setInstruction(existing.data.instructionText); setAudioAssetId(existing.data.instructionAudioAssetId); setOptions(existing.data.options.map(toDraft)); } }, [existing.data]);
  const save = useMutation({ mutationFn: () => isNew ? api.createExercise({ title, instructionText: instruction, instructionAudioAssetId: audioAssetId, options }) : api.updateExercise(exerciseId, { title, instructionText: instruction, instructionAudioAssetId: audioAssetId, options }), onSuccess: result => { cache.invalidateQueries({ queryKey: ["content-exercises"] }); cache.setQueryData(["content-exercise", result.id], result); navigate(`/content/exercises/${result.id}`); } });
  const archive = useMutation({ mutationFn: () => existing.data?.status === "ACTIVE" ? api.archiveExercise(exerciseId) : api.restoreExercise(exerciseId), onSuccess: result => { cache.setQueryData(["content-exercise", exerciseId], result); cache.invalidateQueries({ queryKey: ["content-exercises"] }); } });
  const duplicate = useMutation({ mutationFn: () => api.duplicateExercise(exerciseId), onSuccess: result => { cache.invalidateQueries({ queryKey: ["content-exercises"] }); navigate(`/content/exercises/${result.id}`); } });
  if (!isNew && existing.isLoading) return <PageLoading />; if (existing.error) return <Failure message={messageForError(existing.error)} onRetry={() => void existing.refetch()} />;
  const readOnly = !isNew && existing.data?.ownership === "SYSTEM";
  const upload = async (index: number | "audio", file?: File) => { if (!file) return; setUploading(index); try { const asset = await api.uploadMedia(index === "audio" ? "audio" : "images", file); if (index === "audio") setAudioAssetId(asset.id); else setOptions(current => current.map((option, i) => i === index ? { ...option, imageAssetId: asset.id, imageUrl: asset.url } : option)); } catch (error) { window.alert(messageForError(error)); } finally { setUploading(null); } };
  const setCorrect = (index: number) => setOptions(current => current.map((option, i) => ({ ...option, isCorrect: i === index })));
  return <><Link className="back-link" to="/content/exercises">← К упражнениям</Link><div className="page-heading"><div><p className="eyebrow">Контент · SINGLE_CHOICE</p><h1>{isNew ? "Новое упражнение" : readOnly ? existing.data?.title : "Редактор упражнения"}</h1><p className="muted">От 2 до 6 вариантов и ровно один правильный ответ.</p></div>{readOnly && <button className="primary-button" onClick={() => duplicate.mutate()}>Создать копию</button>}</div>
    <section className="panel narrow"><div className="form-grid"><label className="field"><span>Название</span><input disabled={readOnly} value={title} onChange={event => setTitle(event.target.value)} /></label><label className="field"><span>Инструкция</span><textarea disabled={readOnly} value={instruction} onChange={event => setInstruction(event.target.value)} rows={3} /></label><label className="field"><span>Аудио инструкции (необязательно)</span>{audioAssetId ? <span className="inline-note">Аудио загружено · <button className="text-button" disabled={readOnly} onClick={() => setAudioAssetId(undefined)}>убрать</button></span> : <input disabled={readOnly || uploading === "audio"} type="file" accept="audio/mpeg,audio/mp4,audio/aac,audio/ogg,audio/wav" onChange={event => void upload("audio", event.target.files?.[0])} />}</label></div>
      <h2>Варианты ответа</h2><div className="content-options">{options.map((option, index) => <div className="content-option" key={option.id ?? index}><strong>{index + 1}.</strong><div className="option-image">{option.imageUrl ? <PrivateMediaImage url={option.imageUrl} alt={option.label || "Вариант"} /> : <span>Нет изображения</span>}<input disabled={readOnly || uploading === index} type="file" accept="image/jpeg,image/png,image/webp" onChange={event => void upload(index,event.target.files?.[0])} /></div><label className="field"><span>Название</span><input disabled={readOnly} value={option.label} onChange={event => setOptions(current => current.map((item, i) => i === index ? { ...item, label: event.target.value } : item))} /></label><label className="correct-choice"><input disabled={readOnly} type="radio" checked={option.isCorrect} onChange={() => setCorrect(index)} /> Правильный</label>{!readOnly && options.length > 2 && <button className="text-button danger-text" onClick={() => setOptions(current => current.filter((_, i) => i !== index))}>Удалить</button>}</div>)}</div>
      {!readOnly && options.length < 6 && <button className="secondary-button" onClick={() => setOptions(current => [...current, { label: "", isCorrect: false }])}>+ Добавить вариант</button>}
      {!readOnly && <div className="dialog-actions"><button className="primary-button" disabled={save.isPending || uploading !== null} onClick={() => save.mutate()}>{save.isPending ? "Сохраняем…" : "Сохранить"}</button><Link className="secondary-button" to="/content/exercises">Отмена</Link>{!isNew && <button className="text-button danger-text" disabled={archive.isPending} onClick={() => archive.mutate()}>{existing.data?.status === "ACTIVE" ? "Архивировать" : "Восстановить"}</button>}</div>}{save.error && <p className="form-error">{messageForError(save.error)}</p>}{archive.error && <p className="form-error">{messageForError(archive.error)}</p>}</section></>;
}

export function TemplatesPage() {
  const [scope, setScope] = useState<"ALL" | "SYSTEM" | "CENTER">("ALL"); const [status,setStatus]=useState<"ALL"|"ACTIVE"|"ARCHIVED">("ACTIVE"); const [search,setSearch]=useState("");
  const templates=useQuery({queryKey:["lesson-templates",scope,status,search],queryFn:()=>api.listTemplates({ownership:scope==="ALL"?undefined:scope,status:status==="ALL"?undefined:status,search})});
  if(templates.isLoading)return <PageLoading/>;if(templates.error)return <Failure message={messageForError(templates.error)} onRetry={()=>void templates.refetch()}/>;
  return <><div className="page-heading"><div><p className="eyebrow">Контент</p><h1>Шаблоны занятий</h1><p className="muted">Готовые последовательности упражнений для запуска на планшете.</p></div><Link className="primary-button" to="/content/templates/new">+ Создать шаблон</Link></div><section className="panel"><div className="toolbar"><div className="filter-row">{(["ALL","SYSTEM","CENTER"] as const).map(value=><button key={value} className={`filter ${scope===value?"active":""}`} onClick={()=>setScope(value)}>{value==="ALL"?"Все":value==="SYSTEM"?"Oyla":"Центра"}</button>)}{(["ACTIVE","ARCHIVED","ALL"]as const).map(value=><button key={value} className={`filter ${status===value?"active":""}`} onClick={()=>setStatus(value)}>{value==="ALL"?"Все статусы":value==="ACTIVE"?"Активные":"Архив"}</button>)}</div><label className="search"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Поиск шаблонов"/></label></div><div className="template-grid">{templates.data?.map(template=><TemplateCard key={template.id} template={template}/>)}</div>{!templates.data?.length&&<div className="empty-state"><p>Шаблонов по этим фильтрам пока нет.</p></div>}</section></>;
}

function TemplateCard({template}:{template:LessonTemplate}) { return <Link className="template-card" to={`/content/templates/${template.id}`}><div><strong>{template.name}</strong><p>{template.description || "Без описания"}</p></div><span>{template.exerciseCount} упражнений · {template.ownership === "SYSTEM" ? "Oyla" : "Центр"}</span><span className="status-badge muted-badge">{template.status === "ACTIVE" ? "Активен" : "Архив"}</span></Link>; }

export function TemplateEditorPage() {
  const { templateId="new" }=useParams();const isNew=templateId==="new";const navigate=useNavigate();const cache=useQueryClient();const current=useQuery({queryKey:["lesson-template",templateId],queryFn:()=>api.getTemplate(templateId),enabled:!isNew});const library=useQuery({queryKey:["template-library"],queryFn:()=>api.listExercises({status:"ACTIVE"})});
  const [name,setName]=useState("");const [description,setDescription]=useState("");const [items,setItems]=useState<string[]>([]);const [search,setSearch]=useState("");
  useEffect(()=>{if(current.data){setName(current.data.name);setDescription(current.data.description||"");setItems(current.data.items.sort((a,b)=>a.position-b.position).map(item=>item.exerciseId));}},[current.data]);
  const save=useMutation({mutationFn:()=>isNew?api.createTemplate({name,description:description||undefined,items:items.map(exerciseId=>({exerciseId}))}):api.updateTemplate(templateId,{name,description:description||undefined,items:items.map(exerciseId=>({exerciseId}))}),onSuccess:result=>{cache.invalidateQueries({queryKey:["lesson-templates"]});navigate(`/content/templates/${result.id}`);}});const duplicate=useMutation({mutationFn:()=>api.duplicateTemplate(templateId),onSuccess:result=>{cache.invalidateQueries({queryKey:["lesson-templates"]});navigate(`/content/templates/${result.id}`);}});const archive=useMutation({mutationFn:()=>current.data?.status==="ACTIVE"?api.archiveTemplate(templateId):api.restoreTemplate(templateId),onSuccess:result=>cache.setQueryData(["lesson-template",templateId],result)});
  if(!isNew&&current.isLoading)return <PageLoading/>;if(current.error)return <Failure message={messageForError(current.error)} onRetry={()=>void current.refetch()}/>;const readOnly=!isNew&&current.data?.ownership==="SYSTEM";const visible=(library.data||[]).filter(exercise=>`${exercise.title} ${exercise.instructionText}`.toLowerCase().includes(search.toLowerCase()));const move=(index:number,delta:number)=>setItems(currentItems=>{const next=[...currentItems];const target=index+delta;if(target<0||target>=next.length)return next;[next[index],next[target]]=[next[target],next[index]];return next;});
  return <><Link className="back-link" to="/content/templates">← К шаблонам</Link><div className="page-heading"><div><p className="eyebrow">Контент</p><h1>{isNew?"Новый шаблон":readOnly?current.data?.name:"Конструктор занятия"}</h1><p className="muted">Состав сохраняется атомарно и станет snapshot при запуске занятия.</p></div>{readOnly&&<button className="primary-button" onClick={()=>duplicate.mutate()}>Создать копию</button>}</div><section className="panel"><div className="form-grid"><label className="field"><span>Название</span><input disabled={readOnly} value={name} onChange={event=>setName(event.target.value)}/></label><label className="field"><span>Описание</span><textarea disabled={readOnly} value={description} onChange={event=>setDescription(event.target.value)} rows={2}/></label></div><div className="template-builder"><div><h2>Библиотека упражнений</h2><label className="search"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Поиск"/></label><div className="builder-list">{visible.map(exercise=><button key={exercise.id} disabled={readOnly||items.length>=30} className="builder-item" onClick={()=>setItems(currentItems=>[...currentItems,exercise.id])}><span>{exercise.title}</span><small>{exercise.ownership==="SYSTEM"?"Oyla":"Центр"}</small></button>)}</div></div><div><h2>Состав занятия · {items.length}</h2><div className="builder-list">{items.map((id,index)=>{const exercise=library.data?.find(candidate=>candidate.id===id);return <div className="builder-item static" key={`${id}-${index}`}><span>{index+1}. {exercise?.title||"Упражнение"}</span>{!readOnly&&<div><button className="text-button" onClick={()=>move(index,-1)}>↑</button><button className="text-button" onClick={()=>move(index,1)}>↓</button><button className="text-button danger-text" onClick={()=>setItems(currentItems=>currentItems.filter((_,i)=>i!==index))}>×</button></div>}</div>})}{!items.length&&<p className="muted">Добавьте хотя бы одно упражнение.</p>}</div></div></div>{!readOnly&&<div className="dialog-actions"><button className="primary-button" disabled={save.isPending||!items.length} onClick={()=>save.mutate()}>{save.isPending?"Сохраняем…":"Сохранить"}</button><Link className="secondary-button" to="/content/templates">Отмена</Link>{!isNew&&<button className="text-button danger-text" onClick={()=>archive.mutate()}>{current.data?.status==="ACTIVE"?"Архивировать":"Восстановить"}</button>}</div>}{save.error&&<p className="form-error">{messageForError(save.error)}</p>}</section></>;
}

function defaultOptions(): DraftOption[] { return Array.from({length:4},()=>({label:"",isCorrect:false})).map((option,index)=>({...option,isCorrect:index===0})); }
function toDraft(option:ContentExerciseOption):DraftOption { return {id:option.id,label:option.label||"",imageAssetId:option.imageAssetId,imageUrl:option.imageUrl,isCorrect:option.isCorrect}; }

function PrivateMediaImage({ url, alt }: { url: string; alt: string }) {
  const [objectUrl, setObjectUrl] = useState<string>();
  useEffect(() => { let active = true; let current: string | undefined; void api.mediaBlob(url).then(blob => { if (active) { current = URL.createObjectURL(blob); setObjectUrl(current); } }).catch(() => undefined); return () => { active = false; if (current) URL.revokeObjectURL(current); }; }, [url]);
  return objectUrl ? <img src={objectUrl} alt={alt} /> : <span>Загрузка…</span>;
}
